Resources:
  MyEC2Instance:
    # MYEC2Instance is a name of the resource, we can use any name
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro 
      ImageId: ami-05b10e08d247fb927 # Replace with a valid AMI ID for your region
      AvailabilityZone: us-east-1a  # Replace with a valid AZ for your region